---
title: "District Clusters"
author: "Laura Hinton"
date: "5/18/2022"
output: html_document
---

```{r setup, include=FALSE}
library(beepr)
library(dendextend)
library(tidytext)
library(janitor)
library(factoextra)
library(ggfortify)
library(tidymodels)
library(tidyverse)
library(corrplot)
```

## White-Hispanic Gap

```{r}
districts <- read_csv("merged data v3.csv")

districts_whg <- districts |>
  filter(outlier == 0) |> 
  select(lr_all_ols_whg,
         student_teacher_ratio,
           per_pupil_exp,
           percent_urban,
           percent_suburb,
           percent_town,
           percent_rural,
           percent_city_large,
           percent_city_midsize,
           percent_city_small,
           percent_suburb_large,
           percent_suburb_midsize,
           percent_suburb_small,
           percent_town_fringe,
           percent_town_distant,
           percent_town_remote,
           percent_rural_fringe,
           percent_rural_distant,
           percent_rural_remote,
           percent_native_american,
           percent_asian,
           percent_hispanic,
           percent_black,
           percent_white,
           percent_ecd,
           percent_ell,
           percent_sped,
           total_enrollment,
           diffexpecd_blkwht,
           diffexpecd_hspwht,
           diffexpmin2_blkwht,
           diffexpmin2_hspwht,
           ses_all_bayes,
         pct_stu_iss_black,
         pct_students_ooss_single_black,
         pct_students_ooss_multiple_black,
         pct_expulsions_no_ed_serv_black,
         pct_expulsions_with_ed_black,
         pct_expulsions_no_tol_black,
         pct_students_arrested_black,
         pct_students_ooss_single_hsp,
         pct_students_ooss_multiple_hsp,
         pct_expulsions_no_ed_serv_hsp,
         pct_expulsions_with_ed_hsp,
         pct_expulsions_no_tol_hsp,
         pct_students_arrested_hsp,
         pct_students_ooss_single_white,
         pct_students_ooss_multiple_white,
         pct_expulsions_with_ed_white,
         pct_expulsions_no_tol_white,
         pct_students_arrested_white) |> 
  drop_na()
```

```{r scale}
districts_z_whg <- districts_whg |> 
  mutate(across(everything(), scale))

summary(districts_z_whg)
```

```{r k}
set.seed(1234)

tibble(k = 1:15) |>
  mutate(kmeansmod = map(k, ~ kmeans(districts_z_whg, 
                             .x,
                             nstart = 25,
                             iter.max = 20)),
         glanced = map(kmeansmod, glance)) |>
  unnest(cols = c(glanced)) |>
  ggplot(aes(k, tot.withinss)) +
  geom_line() +
  geom_point()
```

```{r kmeans}
district_clusters_whg <- kmeans(districts_z_whg, 
                        centers = 4, 
                        nstart = 25,
                        iter.max = 20)

district_clusters_whg
```

```{r tidy}
tidy(district_clusters_whg)
```

```{r plot kmeans vars}
tidy(district_clusters_whg) |>
  mutate(cluster = str_c("cluster_", 1:4)) |>
  pivot_longer(cols = -c(cluster, withinss, size),
               names_to = "Interest",
               values_to = "Value") |>
  mutate(importance = Value * Value) |>
  group_by(cluster) |>
  slice_max(importance, n = 10) |>
  ungroup() |>
  mutate(cluster = as.factor(cluster),
         Interest = reorder_within(Interest,
                                   by = importance,
                                   within = cluster)) |>
  ggplot() +
  geom_col(aes(y = Value, 
               x = Interest,
               fill = Interest)) +
  facet_wrap(~ cluster, 
             nrow = 2,
             scales = "free_y") + 
  guides(fill = "none") +
  scale_x_reordered() +
  coord_flip()
```

## White-Black Gap

```{r}
districts_wbg <- districts |>
  filter(outlier == 0) |> 
  select(lr_all_ols_wbg,
         student_teacher_ratio,
           per_pupil_exp,
           percent_urban,
           percent_suburb,
           percent_town,
           percent_rural,
           percent_city_large,
           percent_city_midsize,
           percent_city_small,
           percent_suburb_large,
           percent_suburb_midsize,
           percent_suburb_small,
           percent_town_fringe,
           percent_town_distant,
           percent_town_remote,
           percent_rural_fringe,
           percent_rural_distant,
           percent_rural_remote,
           percent_native_american,
           percent_asian,
           percent_hispanic,
           percent_black,
           percent_white,
           percent_ecd,
           percent_ell,
           percent_sped,
           total_enrollment,
           diffexpecd_blkwht,
           diffexpecd_hspwht,
           diffexpmin2_blkwht,
           diffexpmin2_hspwht,
           ses_all_bayes,
         pct_stu_iss_black,
         pct_students_ooss_single_black,
         pct_students_ooss_multiple_black,
         pct_expulsions_no_ed_serv_black,
         pct_expulsions_with_ed_black,
         pct_expulsions_no_tol_black,
         pct_students_arrested_black,
         pct_students_ooss_single_hsp,
         pct_students_ooss_multiple_hsp,
         pct_expulsions_no_ed_serv_hsp,
         pct_expulsions_with_ed_hsp,
         pct_expulsions_no_tol_hsp,
         pct_students_arrested_hsp,
         pct_students_ooss_single_white,
         pct_students_ooss_multiple_white,
         pct_expulsions_with_ed_white,
         pct_expulsions_no_tol_white,
         pct_students_arrested_white) |> 
  drop_na()
```

```{r scale}
districts_z_wbg <- districts_wbg |> 
  mutate(across(everything(), scale))

summary(districts_z_wbg)
```

```{r k}
set.seed(1234)

tibble(k = 1:15) |>
  mutate(kmeansmod = map(k, ~ kmeans(districts_z_wbg, 
                             .x,
                             nstart = 25,
                             iter.max = 20)),
         glanced = map(kmeansmod, glance)) |>
  unnest(cols = c(glanced)) |>
  ggplot(aes(k, tot.withinss)) +
  geom_line() +
  geom_point()
```

```{r kmeans}
district_clusters_wbg <- kmeans(districts_z_wbg, 
                        centers = 4, 
                        nstart = 25,
                        iter.max = 20)

district_clusters_wbg
```

```{r tidy}
tidy(district_clusters_wbg)
```

```{r plot kmeans vars}
tidy(district_clusters_wbg) |>
  mutate(cluster = str_c("cluster_", 1:4)) |>
  pivot_longer(cols = -c(cluster, withinss, size),
               names_to = "Interest",
               values_to = "Value") |>
  mutate(importance = Value * Value) |>
  group_by(cluster) |>
  slice_max(importance, n = 10) |>
  ungroup() |>
  mutate(cluster = as.factor(cluster),
         Interest = reorder_within(Interest,
                                   by = importance,
                                   within = cluster)) |>
  ggplot() +
  geom_col(aes(y = Value, 
               x = Interest,
               fill = Interest)) +
  facet_wrap(~ cluster, 
             nrow = 2,
             scales = "free_y") + 
  guides(fill = "none") +
  scale_x_reordered() +
  coord_flip()
```

## ECD-Non-ECD Gap

```{r}
districts_neg <- districts |>
  filter(outlier == 0) |> 
  select(lr_all_ols_neg,
         student_teacher_ratio,
           per_pupil_exp,
           percent_urban,
           percent_suburb,
           percent_town,
           percent_rural,
           percent_city_large,
           percent_city_midsize,
           percent_city_small,
           percent_suburb_large,
           percent_suburb_midsize,
           percent_suburb_small,
           percent_town_fringe,
           percent_town_distant,
           percent_town_remote,
           percent_rural_fringe,
           percent_rural_distant,
           percent_rural_remote,
           percent_native_american,
           percent_asian,
           percent_hispanic,
           percent_black,
           percent_white,
           percent_ecd,
           percent_ell,
           percent_sped,
           total_enrollment,
           diffexpecd_blkwht,
           diffexpecd_hspwht,
           diffexpmin2_blkwht,
           diffexpmin2_hspwht,
           ses_all_bayes,
         pct_stu_iss_black,
         pct_students_ooss_single_black,
         pct_students_ooss_multiple_black,
         pct_expulsions_no_ed_serv_black,
         pct_expulsions_with_ed_black,
         pct_expulsions_no_tol_black,
         pct_students_arrested_black,
         pct_students_ooss_single_hsp,
         pct_students_ooss_multiple_hsp,
         pct_expulsions_no_ed_serv_hsp,
         pct_expulsions_with_ed_hsp,
         pct_expulsions_no_tol_hsp,
         pct_students_arrested_hsp,
         pct_students_ooss_single_white,
         pct_students_ooss_multiple_white,
         pct_expulsions_with_ed_white,
         pct_expulsions_no_tol_white,
         pct_students_arrested_white) |> 
  drop_na()
```

```{r scale}
districts_z_neg <- districts_neg |> 
  mutate(across(everything(), scale))

summary(districts_z_neg)
```

```{r k}
set.seed(1234)

tibble(k = 1:15) |>
  mutate(kmeansmod = map(k, ~ kmeans(districts_z_neg, 
                             .x,
                             nstart = 25,
                             iter.max = 20)),
         glanced = map(kmeansmod, glance)) |>
  unnest(cols = c(glanced)) |>
  ggplot(aes(k, tot.withinss)) +
  geom_line() +
  geom_point()
```

```{r kmeans}
district_clusters_neg <- kmeans(districts_z_neg, 
                        centers = 4, 
                        nstart = 25,
                        iter.max = 20)

district_clusters_neg
```

```{r tidy}
tidy(district_clusters_neg)
```

```{r plot kmeans vars}
tidy(district_clusters_neg) |>
  mutate(cluster = str_c("cluster_", 1:4)) |>
  pivot_longer(cols = -c(cluster, withinss, size),
               names_to = "Interest",
               values_to = "Value") |>
  mutate(importance = Value * Value) |>
  group_by(cluster) |>
  slice_max(importance, n = 10) |>
  ungroup() |>
  mutate(cluster = as.factor(cluster),
         Interest = reorder_within(Interest,
                                   by = importance,
                                   within = cluster)) |>
  ggplot() +
  geom_col(aes(y = Value, 
               x = Interest,
               fill = Interest)) +
  facet_wrap(~ cluster, 
             nrow = 2,
             scales = "free_y") + 
  guides(fill = "none") +
  scale_x_reordered() +
  coord_flip()
```
