---
title: "Regression"
author: "Laura Hinton"
date: "5/18/2022"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(haven)
library(broom)
library(fastDummies)
library(stargazer)
library(glmnet)
library(tidymodels)
library(corrplot)

merged_data_clusters <- read_csv("merged_data_clusters.csv")

```


```{r correlation plot}
# correlation plot for segregation variables in cluster one
col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))

cluster_one |>
  select(-lr_all_ols_whg) |>
  cor() |>
  corrplot(method = "color",
           type = "upper",
           diag = FALSE,
           col=col(200),
           addCoef.col = "black",
           title = "Correlation Plot",
           mar=c(0,0,1,0))
```


## Normal Regression with Clusters - DID NOT USE IN FINAL

```{r select data}
reg_data <- merged_data_clusters |> 
  select(lr_all_ols_whg,
         lr_all_ols_wbg,
         lr_all_ols_neg,
         cluster_lab) |> 
  drop_na(cluster_lab)

reg_data <- reg_data |> 
  dummy_cols("cluster_lab", remove_selected_columns = TRUE)

# whg
reg_whg <- lm(lr_all_ols_whg ~ cluster_lab_asian_suburb +
            cluster_lab_low_income_town +
            cluster_lab_rural_white +
            cluster_lab_urban_poc,
          data = reg_data)

summary(reg_whg)

# wbg
reg_wbg <- lm(lr_all_ols_wbg ~ cluster_lab_asian_suburb +
            cluster_lab_low_income_town +
            cluster_lab_rural_white +
            cluster_lab_urban_segregated,
          data = reg_data)

summary(reg_wbg)

# neg
reg_neg <- lm(lr_all_ols_neg ~ cluster_lab_asian_suburb +
            cluster_lab_low_income_town +
            cluster_lab_rural_white +
            cluster_lab_urban_segregated,
          data = reg_data)

summary(reg_neg)

# tables
varnames = c("Intercept", "Cluster: Asian Suburb", "Cluster: Low-Income Town", "Cluster: Rural White", "Cluster: Urban Segregated")

stargazer(reg_whg, type = "html", out = "whg_regressiontable.html", title = "White-Hispanic Learning Rate Gaps vs. District Characteristics", covariate.labels = varnames, dep.var.caption = "", dep.var.labels = "", intercept.bottom = FALSE, notes.label = "")

stargazer(reg_wbg, type = "html", out = "wbg_regressiontable.html", title = "White-Black Learning Rate Gaps vs. District Characteristics", covariate.labels = varnames, dep.var.caption = "", dep.var.labels = "", intercept.bottom = FALSE, notes.label = "")

stargazer(reg_neg, type = "html", out = "neg_regressiontable.html", title = "ECD-Non-ECD Learning Rate Gaps vs. District Characteristics", covariate.labels = varnames, dep.var.caption = "", dep.var.labels = "", intercept.bottom = FALSE, notes.label = "")

```


```{r}
# correlation table
# normal regression
```


```{r cluster datasets}
cluster_one <- merged_data_clusters |> 
  filter(cluster == 1)  |> 
  select(cluster, cluster_lab, lr_all_ols_wbg,
         lr_all_ols_neg, 
        lr_all_ols_whg,
         student_teacher_ratio,
           per_pupil_exp,
           diffexpecd_blkwht,
           diffexpecd_hspwht,
           diffexpmin2_blkwht,
           diffexpmin2_hspwht,
         hsflnfl,
         hsecdnec,
         rswhtblk,
         rswhthsp,
         rsflnfl,
         rsecdnec,
        hswhthsp,
        hswhtblk) |> 
  drop_na()

cluster_two <- merged_data_clusters |> 
  filter(cluster == 2)  |> 
  select(cluster, cluster_lab, lr_all_ols_wbg,
         lr_all_ols_neg, 
        lr_all_ols_whg,
         student_teacher_ratio,
           per_pupil_exp,
           diffexpecd_blkwht,
           diffexpecd_hspwht,
           diffexpmin2_blkwht,
           diffexpmin2_hspwht,
         hsflnfl,
         hsecdnec,
         rswhtblk,
         rswhthsp,
         rsflnfl,
         rsecdnec,
        hswhtblk,
        hswhthsp) |> 
  drop_na()

cluster_three <- merged_data_clusters |> 
  filter(cluster == 3)  |> 
  select(cluster, cluster_lab, lr_all_ols_whg, lr_all_ols_wbg,
         lr_all_ols_neg,
         student_teacher_ratio,
           per_pupil_exp,
           diffexpecd_blkwht,
           diffexpecd_hspwht,
           diffexpmin2_blkwht,
           diffexpmin2_hspwht,
         hsflnfl,
         hsecdnec,
         rswhtblk,
         rswhthsp,
         rsflnfl,
         rsecdnec,
        hswhtblk,
        hswhthsp) |> 
  drop_na()

cluster_four <- merged_data_clusters |> 
  filter(cluster == 4)  |> 
  select(cluster, cluster_lab, lr_all_ols_whg, lr_all_ols_wbg,
         lr_all_ols_neg,
         student_teacher_ratio,
           per_pupil_exp,
           diffexpecd_blkwht,
           diffexpecd_hspwht,
           diffexpmin2_blkwht,
           diffexpmin2_hspwht,
         hsflnfl,
         hsecdnec,
         rswhtblk,
         rswhthsp,
         rsflnfl,
         rsecdnec,
        hswhtblk,
        hswhthsp) |> 
  drop_na()

```



```{r}
# cluster one
cluster_one_reg_whg <- lm(lr_all_ols_whg ~ student_teacher_ratio + per_pupil_exp +
                            diffexpecd_hspwht + diffexpmin2_hspwht + rswhthsp + hswhthsp,
         data = cluster_one)

summary(cluster_one_reg_whg)

cluster_one_reg_wbg <- lm(lr_all_ols_wbg ~ student_teacher_ratio + per_pupil_exp +
                            diffexpecd_blkwht + diffexpmin2_blkwht + rswhtblk + hswhtblk,
         data = cluster_one)

summary(cluster_one_reg_wbg)

cluster_one_reg_neg <- lm(lr_all_ols_neg ~ student_teacher_ratio + per_pupil_exp +
                            hsflnfl + hsecdnec + rsflnfl + rsecdnec,
         data = cluster_one)

summary(cluster_one_reg_neg)

# cluster two
cluster_two_reg_whg <- lm(lr_all_ols_whg ~ student_teacher_ratio + per_pupil_exp +
                            diffexpecd_hspwht + diffexpmin2_hspwht + rswhthsp + hswhthsp,
         data = cluster_two)

summary(cluster_two_reg_whg)

cluster_two_reg_wbg <- lm(lr_all_ols_wbg ~ student_teacher_ratio + per_pupil_exp +
                            diffexpecd_blkwht + diffexpmin2_blkwht + rswhtblk + hswhtblk,
         data = cluster_two)

summary(cluster_two_reg_wbg)

cluster_two_reg_neg <- lm(lr_all_ols_neg ~ student_teacher_ratio + per_pupil_exp +
                            hsflnfl + hsecdnec + rsflnfl + rsecdnec,
         data = cluster_two)

summary(cluster_two_reg_neg)

# cluster three
cluster_three_reg_whg <- lm(lr_all_ols_whg ~ student_teacher_ratio + per_pupil_exp +
                            diffexpecd_hspwht + diffexpmin2_hspwht + rswhthsp + hswhthsp,
         data = cluster_three)

summary(cluster_three_reg_whg)

cluster_three_reg_wbg <- lm(lr_all_ols_wbg ~ student_teacher_ratio + per_pupil_exp +
                            diffexpecd_blkwht + diffexpmin2_blkwht + rswhtblk + hswhtblk,
         data = cluster_three)

summary(cluster_three_reg_wbg)

cluster_three_reg_neg <- lm(lr_all_ols_neg ~ student_teacher_ratio + per_pupil_exp +
                            hsflnfl + hsecdnec + rsflnfl + rsecdnec,
         data = cluster_three)

summary(cluster_three_reg_neg)

# cluster four
cluster_four_reg_whg <- lm(lr_all_ols_whg ~ student_teacher_ratio + per_pupil_exp +
                            diffexpecd_hspwht + diffexpmin2_hspwht + rswhthsp + hswhthsp,
         data = cluster_four)

summary(cluster_four_reg_whg)

cluster_four_reg_wbg <- lm(lr_all_ols_wbg ~ student_teacher_ratio + per_pupil_exp +
                            diffexpecd_blkwht + diffexpmin2_blkwht + rswhtblk + hswhtblk,
         data = cluster_four)

summary(cluster_four_reg_wbg)

cluster_four_reg_neg <- lm(lr_all_ols_neg ~ student_teacher_ratio + per_pupil_exp +
                            hsflnfl + hsecdnec + rsflnfl + rsecdnec,
         data = cluster_four)

summary(cluster_four_reg_neg)
```


```{r regression tables by outcome}
cluster_names = c("Asian Suburb",  "Rural White", "Urban POC", "Low-Income Town")

whg_varnames = c("Intercept", "Student-Teacher Ratio", "Per-Pupil Expenditures", "Hispanic-White Difference in Exposure to ECD Students", "Hispanic-White Difference in Exposure to Minority Students", "Relative Diversity Index Between Schools: White/Hispanic","Information Index Between Schools: White/Hispanic")

stargazer(cluster_one_reg_whg, cluster_two_reg_whg, cluster_three_reg_whg, cluster_four_reg_whg, type = "html", out = "whg_regressiontable.html", title = "White-Hispanic Learning Rate Gaps by Segregation Measures", covariate.labels = whg_varnames, dep.var.caption = "", dep.var.labels = "", intercept.bottom = FALSE, notes.label = "", column.labels = cluster_names)

wbg_varnames = c("Intercept", "Student-Teacher Ratio", "Per-Pupil Expenditures", "Black-White Difference in Exposure to ECD Students", "Black-White Difference in Exposure to Minority Students", "Relative Diversity Index Between Schools: White/Black","Information Index Between Schools: White/Black")

stargazer(cluster_one_reg_wbg, cluster_two_reg_wbg, cluster_three_reg_wbg, cluster_four_reg_wbg, type = "html", out = "wbg_regressiontable.html", title = "White-Black Learning Rate Gaps by Segregation Measures", covariate.labels = wbg_varnames, dep.var.caption = "", dep.var.labels = "", intercept.bottom = FALSE, notes.label = "", column.labels = cluster_names)

neg_varnames = c("Intercept", "Student-Teacher Ratio", "Per-Pupil Expenditures", "Information Index Between Schools: Free Lunch/Non Free Lunch", "Information Index Between Schools: ECD/Non-ECD", "Relative Diversity Index Between Schools: Free Lunch/Non Free Lunch", "Relative Diversity Index Between Schools: ECD/Non-ECD")

stargazer(cluster_one_reg_neg, cluster_two_reg_neg, cluster_three_reg_neg, cluster_four_reg_neg, type = "html", out = "neg_regressiontable.html", title = "ECD-Non-ECD Learning Rate Gaps by Segregation Measures", covariate.labels = neg_varnames, dep.var.caption = "", dep.var.labels = "", intercept.bottom = FALSE, notes.label = "", column.labels = cluster_names)
```

## Regularized Regression with Clusters - DID NOT USE IN FINAL


```{r cluster one}

# outcomes: lr_all_ols_whg, lr_all_ols_wbg, lr_all_ols_neg

# split data

set.seed(1234)

cluster_one_split <- 
  initial_split(cluster_one, 
                prop = .8,
                strata = lr_all_ols_whg)

cluster_one_train <- training(cluster_one_split)

cluster_one_test <- testing(cluster_one_split)

cluster_one_recipe <- 
  recipe(lr_all_ols_whg ~ ., 
         data = cluster_one_train) |> 
  step_rm(lr_all_ols_wbg, lr_all_ols_neg, cluster_lab, cluster)

cluster_one_recipe |> 
  prep(training = cluster_one_train) |> 
  bake(new_data = NULL) |> 
  glimpse()

ridge_spec <- 
  linear_reg(penalty = 1, mixture = 0) |>
  set_engine("glmnet") |>
  set_mode("regression")

ridge_wf <- 
  workflow() |> 
  add_model(ridge_spec) |> 
  add_recipe(cluster_one_recipe)

ridge_wf

ridge_fit <- 
  fit(ridge_wf, 
      data = cluster_one_train)

tidy(ridge_fit)

tidy(ridge_fit) |> 
  arrange(abs(estimate)) |> 
  filter(term != "(Intercept)") |> 
  slice_tail(n = 10) |> 
  ggplot(aes(x = reorder(term, estimate),
             y = estimate,
             fill = estimate > 0)) +
  geom_col() +
  coord_flip()

regularization_spec <- 
  linear_reg(penalty = tune(), mixture = tune()) |>
  set_engine("glmnet") |> 
  set_mode("regression")

grid <- 
  expand_grid(penalty = seq(0, 0.1, by = 0.005), # these values are used often
              mixture = seq(0, 1, by = 0.2))

cluster_one_cv <- 
  vfold_cv(cluster_one_train, v = 3)

cluster_one_results <- 
  tune_grid(regularization_spec,
            preprocessor = cluster_one_recipe,
            grid = grid,
            resamples = cluster_one_cv)

cluster_one_results |> 
  collect_metrics()  |> 
  filter(.metric == "rmse") |>
  ggplot(aes(x = penalty, y = mean, color = as.factor(mixture))) + 
  geom_point() + 
  geom_line() + 
  ylab("RMSE")

cluster_one_best_model <- 
  cluster_one_results |>   
  select_best(metric = "rmse")

cluster_one_best_model

cluster_one_final_spec <- 
  linear_reg(penalty = 0.02, mixture = 0.2) |> 
  set_engine("glmnet") |> 
  set_mode("regression")

cluster_one_final_wf <- 
  workflow()  |> 
  add_model(cluster_one_final_spec)  |> 
  add_recipe(cluster_one_recipe)

cluster_one_final_wf

cluster_one_final_fit <- 
  cluster_one_final_wf |>  
  fit(data = cluster_one_train)

all_cluster_one_variables <- tidy(cluster_one_final_fit)
# kicked out everything?

tidy(cluster_one_final_fit) |> 
  arrange(abs(estimate))|> 
  slice_tail(n = 10) |> 
  ggplot(aes(x = term,
             y = estimate)) +
  geom_col() +
  coord_flip()
```


```{r cluster two}
# outcomes: lr_all_ols_whg, lr_all_ols_wbg, lr_all_ols_neg

# split data

set.seed(1234)

cluster_two_split <- 
  initial_split(cluster_two, 
                prop = .8,
                strata = lr_all_ols_whg)

cluster_two_train <- training(cluster_two_split)

cluster_two_test <- testing(cluster_two_split)

cluster_two_recipe <- 
  recipe(lr_all_ols_whg ~ ., 
         data = cluster_two_train) |> 
  step_rm(lr_all_ols_wbg, lr_all_ols_neg, cluster_lab, cluster)

cluster_two_recipe |> 
  prep(training = cluster_two_train) |> 
  bake(new_data = NULL) |> 
  glimpse()

ridge_spec <- 
  linear_reg(penalty = 1, mixture = 0) |>
  set_engine("glmnet") |>
  set_mode("regression")

ridge_wf <- 
  workflow() |> 
  add_model(ridge_spec) |> 
  add_recipe(cluster_two_recipe)

ridge_wf

ridge_fit <- 
  fit(ridge_wf, 
      data = cluster_two_train)

tidy(ridge_fit)

tidy(ridge_fit) |> 
  arrange(abs(estimate)) |> 
  filter(term != "(Intercept)") |> 
  slice_tail(n = 10) |> 
  ggplot(aes(x = reorder(term, estimate),
             y = estimate,
             fill = estimate > 0)) +
  geom_col() +
  coord_flip()

regularization_spec <- 
  linear_reg(penalty = tune(), mixture = tune()) |>
  set_engine("glmnet") |> 
  set_mode("regression")

grid <- 
  expand_grid(penalty = seq(0, 0.1, by = 0.005), # these values are used often
              mixture = seq(0, 1, by = 0.2))

cluster_two_cv <- 
  vfold_cv(cluster_two_train, v = 3)

cluster_two_results <- 
  tune_grid(regularization_spec,
            preprocessor = cluster_two_recipe,
            grid = grid,
            resamples = cluster_two_cv)

cluster_two_results |> 
  collect_metrics()  |> 
  filter(.metric == "rmse") |>
  ggplot(aes(x = penalty, y = mean, color = as.factor(mixture))) + 
  geom_point() + 
  geom_line() + 
  ylab("RMSE")

cluster_two_best_model <- 
  cluster_two_results |>   
  select_best(metric = "rmse")

cluster_two_best_model

cluster_two_final_spec <- 
  linear_reg(penalty = 0.025, mixture = 0) |> 
  set_engine("glmnet") |> 
  set_mode("regression")

cluster_two_final_wf <- 
  workflow()  |> 
  add_model(cluster_two_final_spec)  |> 
  add_recipe(cluster_two_recipe)

cluster_two_final_wf

cluster_two_final_fit <- 
  cluster_two_final_wf |>  
  fit(data = cluster_two_train)

all_cluster_two_variables <- tidy(cluster_two_final_fit)

tidy(cluster_two_final_fit) |> 
  arrange(abs(estimate))|> 
  slice_tail(n = 10) |> 
  ggplot(aes(x = term,
             y = estimate)) +
  geom_col() +
  coord_flip()
```


```{r cluster three}

# outcomes: lr_all_ols_whg, lr_all_ols_wbg, lr_all_ols_neg

# split data
set.seed(1234)

cluster_three_split <- 
  initial_split(cluster_three, 
                prop = .8,
                strata = lr_all_ols_whg)

cluster_three_train <- training(cluster_three_split)

cluster_three_test <- testing(cluster_three_split)

cluster_three_recipe <- 
  recipe(lr_all_ols_whg ~ ., 
         data = cluster_three_train) |> 
  step_rm(lr_all_ols_wbg, lr_all_ols_neg, cluster_lab, cluster)

cluster_three_recipe |> 
  prep(training = cluster_three_train) |> 
  bake(new_data = NULL) |> 
  glimpse()

ridge_spec <- 
  linear_reg(penalty = 1, mixture = 0) |>
  set_engine("glmnet") |>
  set_mode("regression")

ridge_wf <- 
  workflow() |> 
  add_model(ridge_spec) |> 
  add_recipe(cluster_three_recipe)

ridge_wf

ridge_fit <- 
  fit(ridge_wf, 
      data = cluster_three_train)

tidy(ridge_fit)

tidy(ridge_fit) |> 
  arrange(abs(estimate)) |> 
  filter(term != "(Intercept)") |> 
  slice_tail(n = 10) |> 
  ggplot(aes(x = reorder(term, estimate),
             y = estimate,
             fill = estimate > 0)) +
  geom_col() +
  coord_flip()

regularization_spec <- 
  linear_reg(penalty = tune(), mixture = tune()) |>
  set_engine("glmnet") |> 
  set_mode("regression")

grid <- 
  expand_grid(penalty = seq(0, 0.1, by = 0.005), # these values are used often
              mixture = seq(0, 1, by = 0.2))

cluster_three_cv <- 
  vfold_cv(cluster_three_train, v = 3)

cluster_three_results <- 
  tune_grid(regularization_spec,
            preprocessor = cluster_three_recipe,
            grid = grid,
            resamples = cluster_three_cv)

cluster_three_results |> 
  collect_metrics()  |> 
  filter(.metric == "rmse") |>
  ggplot(aes(x = penalty, y = mean, color = as.factor(mixture))) + 
  geom_point() + 
  geom_line() + 
  ylab("RMSE")

cluster_three_best_model <- 
  cluster_three_results |>   
  select_best(metric = "rmse")

cluster_three_best_model

cluster_three_final_spec <- 
  linear_reg(penalty = 0.005, mixture = 0.2) |> 
  set_engine("glmnet") |> 
  set_mode("regression")

cluster_three_final_wf <- 
  workflow()  |> 
  add_model(cluster_three_final_spec)  |> 
  add_recipe(cluster_three_recipe)

cluster_three_final_wf

cluster_three_final_fit <- 
  cluster_three_final_wf |>  
  fit(data = cluster_three_train)

all_cluster_three_variables <- tidy(cluster_three_final_fit)
#kicked out everything?

tidy(cluster_three_final_fit) |> 
  arrange(abs(estimate))|> 
  slice_tail(n = 10) |> 
  ggplot(aes(x = term,
             y = estimate)) +
  geom_col() +
  coord_flip()
```

```{r}
hist(merged_data_clusters$diffexpecd_blkwht)
hist(merged_data_clusters$diffexpecd_hspwht)
hist(merged_data_clusters$diffexpmin2_blkwht)
hist(merged_data_clusters$diffexpmin2_hspwht)

sd(merged_data_clusters$diffexpmin2_hspwht, na.rm = T)
  
```

