---
title: "subset selection"
author: "Lucy Caffrey-Maffei"
date: "5/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(dplyr)
library(tidyr)
library(caret)
library(leaps)
library(MASS)
```

```{r datasets}

merged_data <- read_csv("~/Documents/Stanford/EDS Seminar/EDS Group Project/school-integration-project/data/merged data.csv")

#white - hispanic gap
whg <- merged_data |>
  filter(outlier == 0) |> 
  select(lr_all_ols_whg,
           student_teacher_ratio,
           per_pupil_exp,
           percent_urban,
           percent_suburb,
           percent_town,
           percent_rural,
           percent_city_large,
           percent_city_midsize,
           percent_city_small,
           percent_suburb_large,
           percent_suburb_midsize,
           percent_suburb_small,
           percent_town_fringe,
           percent_town_distant,
           percent_town_remote,
           percent_rural_fringe,
           percent_rural_distant,
           percent_rural_remote,
           percent_native_american,
           percent_asian,
           percent_hispanic,
           percent_black,
           percent_white,
           percent_ecd,
           percent_ell,
           percent_sped,
           total_enrollment,
           #ses_black_bayes,
           #ses_hsp_bayes,
           #ses_white_bayes,
           diffexpecd_blkwht,
           diffexpecd_hspwht,
           diffexpmin2_blkwht,
           diffexpmin2_hspwht,
           #sesavgall,
           #diffexpmin2_asnwht,
           #diffexpmin2_namwht,
           ses_all_bayes,
         pct_stu_iss_black,
         pct_students_ooss_single_black,
         pct_students_ooss_multiple_black,
         pct_expulsions_no_ed_serv_black,
         pct_expulsions_with_ed_black,
         pct_expulsions_no_tol_black,
         pct_students_arrested_black,
         pct_students_ooss_single_hsp,
         pct_students_ooss_multiple_hsp,
         pct_expulsions_no_ed_serv_hsp,
         #pct_expulsions_with_ed_serv_hsp,
         pct_expulsions_with_ed_hsp,
         pct_expulsions_no_tol_hsp,
         pct_students_arrested_hsp,
         pct_students_ooss_single_white,
         pct_students_ooss_multiple_white,
         #pct_expulsions_no_ed_serv_white,
         pct_expulsions_with_ed_white,
         pct_expulsions_no_tol_white,
         pct_students_arrested_white) |> 
  drop_na()

wbg <- merged_data |>
  filter(outlier == 0) |> 
  select(lr_all_ols_wbg,
           student_teacher_ratio,
           per_pupil_exp,
           percent_urban,
           percent_suburb,
           percent_town,
           percent_rural,
           percent_city_large,
           percent_city_midsize,
           percent_city_small,
           percent_suburb_large,
           percent_suburb_midsize,
           percent_suburb_small,
           percent_town_fringe,
           percent_town_distant,
           percent_town_remote,
           percent_rural_fringe,
           percent_rural_distant,
           percent_rural_remote,
           percent_native_american,
           percent_asian,
           percent_hispanic,
           percent_black,
           percent_white,
           percent_ecd,
           percent_ell,
           percent_sped,
           total_enrollment,
           #ses_black_bayes,
           #ses_hsp_bayes,
           #ses_white_bayes,
           diffexpecd_blkwht,
           diffexpecd_hspwht,
           diffexpmin2_blkwht,
           diffexpmin2_hspwht,
           #sesavgall,
           #diffexpmin2_asnwht,
           #diffexpmin2_namwht,
           ses_all_bayes,
         pct_stu_iss_black,
         pct_students_ooss_single_black,
         pct_students_ooss_multiple_black,
         pct_expulsions_no_ed_serv_black,
         pct_expulsions_with_ed_black,
         pct_expulsions_no_tol_black,
         pct_students_arrested_black,
         pct_students_ooss_single_hsp,
         pct_students_ooss_multiple_hsp,
         pct_expulsions_no_ed_serv_hsp,
         #pct_expulsions_with_ed_serv_hsp,
         pct_expulsions_with_ed_hsp,
         pct_expulsions_no_tol_hsp,
         pct_students_arrested_hsp,
         pct_students_ooss_single_white,
         pct_students_ooss_multiple_white,
         #pct_expulsions_no_ed_serv_white,
         pct_expulsions_with_ed_white,
         pct_expulsions_no_tol_white,
         pct_students_arrested_white) |> 
  drop_na()

neg <- merged_data |>
  filter(outlier == 0) |> 
  select(lr_all_ols_neg,
           student_teacher_ratio,
           per_pupil_exp,
           percent_urban,
           percent_suburb,
           percent_town,
           percent_rural,
           percent_city_large,
           percent_city_midsize,
           percent_city_small,
           percent_suburb_large,
           percent_suburb_midsize,
           percent_suburb_small,
           percent_town_fringe,
           percent_town_distant,
           percent_town_remote,
           percent_rural_fringe,
           percent_rural_distant,
           percent_rural_remote,
           percent_native_american,
           percent_asian,
           percent_hispanic,
           percent_black,
           percent_white,
           percent_ecd,
           percent_ell,
           percent_sped,
           total_enrollment,
           #ses_black_bayes,
           #ses_hsp_bayes,
           #ses_white_bayes,
           diffexpecd_blkwht,
           diffexpecd_hspwht,
           diffexpmin2_blkwht,
           diffexpmin2_hspwht,
           #sesavgall,
           #diffexpmin2_asnwht,
           #diffexpmin2_namwht,
           ses_all_bayes,
         pct_stu_iss_black,
         pct_students_ooss_single_black,
         pct_students_ooss_multiple_black,
         pct_expulsions_no_ed_serv_black,
         pct_expulsions_with_ed_black,
         pct_expulsions_no_tol_black,
         pct_students_arrested_black,
         pct_students_ooss_single_hsp,
         pct_students_ooss_multiple_hsp,
         pct_expulsions_no_ed_serv_hsp,
         #pct_expulsions_with_ed_serv_hsp,
         pct_expulsions_with_ed_hsp,
         pct_expulsions_no_tol_hsp,
         pct_students_arrested_hsp,
         pct_students_ooss_single_white,
         pct_students_ooss_multiple_white,
         #pct_expulsions_no_ed_serv_white,
         pct_expulsions_with_ed_white,
         pct_expulsions_no_tol_white,
         pct_students_arrested_white) |> 
  drop_na()

```

```{r forward and backward stepwise selection - whg}

set.seed(123)

# k-fold cross validation

train_control_whg <- trainControl(method = "cv", number = 10)

#train the model
step_model_whg <- train(lr_all_ols_whg ~ ., data = whg, 
                        method = "leapSeq",
                        tuneGrid = data.frame(nvmax = 1:50),
                        trControl = train_control_whg)

#r^2 and RMSE for all different possibilities of variables
step_model_whg$results

#best model = 17 predictors
step_model_whg$bestTune

#predictors included in each # of variables
summary(step_model_whg$finalModel)

#regression coefficients for best model
coef(step_model_whg$finalModel, 11)
```
