---
title: "summary statistics"
author: "Lucy Caffrey-Maffei"
date: '2022-06-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(dplyr)
library(tidyverse)
library(ggplot2)
library(haven)
library(broom)
library(fastDummies)
library(stargazer)
library(glmnet)
library(tidymodels)

merged_data <- read_csv("merged data.csv")
final <- merged_data |>
  filter(outlier != 1) |>
  select(lr_all_ols_whg,
         lr_all_ols_wbg,
         lr_all_ols_neg,
         student_teacher_ratio,
                per_pupil_exp,
                percent_urban,
                percent_suburb,
                percent_town,
                percent_rural,
                percent_city_large,
                percent_city_midsize,
                percent_city_small,
                percent_suburb_large,
                percent_suburb_midsize,
                percent_suburb_small,
                percent_town_fringe,
                percent_town_distant,
                percent_town_remote,
                percent_rural_fringe,
                percent_rural_distant,
                percent_rural_remote,
                percent_native_american,
                percent_asian,
                percent_hispanic,
                percent_black,
                percent_white,
                percent_ecd,
                percent_ell,
                percent_sped,
                total_enrollment,
                diffexpecd_blkwht,
                diffexpecd_hspwht,
                diffexpmin2_blkwht,
                diffexpmin2_hspwht,
                ses_all_bayes,
                pct_stu_iss_black,
                pct_students_ooss_single_black,
                pct_students_ooss_multiple_black,
                pct_expulsions_no_ed_serv_black,
                pct_expulsions_with_ed_black,
                pct_expulsions_no_tol_black,
                pct_students_arrested_black,
                pct_students_ooss_single_hsp,
                pct_students_ooss_multiple_hsp,
                pct_expulsions_no_ed_serv_hsp,
                pct_expulsions_with_ed_hsp,
                pct_expulsions_no_tol_hsp,
                pct_students_arrested_hsp,
                pct_students_ooss_single_white,
                pct_students_ooss_multiple_white,
                pct_expulsions_with_ed_white,
                pct_expulsions_no_tol_white,
                pct_students_arrested_white,
                hsflnfl,
                hsecdnec,
                hswhtblk,
                hswhthsp,
                rswhtblk,
                rswhthsp,
                rsflnfl,
                rsecdnec)
```

```{r sum stats}

summary(final)


```
